name: Create Expired CheckIns in advance
on:
  schedule:
    - cron: "0 16 * * SUN-THU"
jobs:
  test:
    timeout-minutes: 60
    runs-on: moj-cloud-platform
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Clean npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Run Playwright tests
      id: tests
      run: npx bddgen && npx playwright test -g "@expired @create"  --workers=1 --retries=0
      env:
        TZ: Europe/London
        ENV: test

        # URLs
        DELIUS_URL: https://ndelius.test.probation.service.justice.gov.uk
        MANAGE_PEOPLE_ON_PROBATION_URL: https://manage-people-on-probation-dev.hmpps.service.justice.gov.uk
        MAS_API_URL: https://manage-supervision-and-delius-dev.hmpps.service.justice.gov.uk
        E_SUPERVISION_API_URL: https://esupervision-api-dev.hmpps.service.justice.gov.uk
        SIGN_IN_URL: https://sign-in-dev.hmpps.service.justice.gov.uk
        OUTLOOK_API_URL: https://probation-supervision-appointments-api-dev.hmpps.service.justice.gov.uk

        # Credentials
        DELIUS_USERNAME: ${{ secrets.E2E_DELIUS_USERNAME }}
        DELIUS_PASSWORD: ${{ secrets.E2E_DELIUS_PASSWORD }}
        API_USERNAME: ${{ secrets.API_USERNAME }}
        API_PASSWORD: ${{ secrets.API_PASSWORD }}


    - name: Publish JUnit report
      if: always()
      uses: mikepenz/action-junit-report@cf701569b05ccdd861a76b8607a66d76f6fd4857 # v5.5.1
      id: junit
      with:
        check_name: End-to-end test results
        report_paths: junit.xml
